# Generated by Django 2.1.3 on 2018-11-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='lists',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.CharField(max_length=400),
        ),
    ]
